# Site settings
title: Felix the Tech Cat
url: "https://felixchr.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: ""
#timezone: Asia/Chongqing
description: >
  Felix's tech note site.

# Your information
email: felix.chr@gmail.com
author: Felix Cao
avatar: "/images/avatar.jpg"
profile: Felix Cao.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:felix.chr@gmail.com"
  GitHub: "https://github.com/felixchr"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    # Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
